application: gae-exercises
version: 5
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /ico/favicon\.ico
  static_files: ico/favicon.ico
  upload: ico/favicon\.ico

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
